In [2]:
# importamos librerias necesarias
%matplotlib inline

import matplotlib.pyplot as plt
import numpy as np 
import pandas as pd 

In [39]:
import csv
with open('datapronabeclimpio.csv', 'r') as csvfile:
    becarios_reader = csv.reader(csvfile, delimiter=',')
    
    # Importamos el dataset como array de numpy
    becarios_dataset = np.array([ row for row in becarios_reader])   #becarios_dataset

In [40]:
print(becarios_dataset)

[['' 'convocatoria' 'region' ..., 'institucionsede' 'carreradescripcion'
  'genero']
 ['0' 'Beca 18 Modalidad Ordinaria 2012' 'LIMA' ..., 'SEDE LIMA'
  'INGENIERIA GEOLOGICA' 'MASCULINO']
 ['1' 'Beca 18 Modalidad Ordinaria 2012' 'LIMA' ..., 'SEDE LIMA'
  'INGENIERIA GEOGRAFICA' 'MASCULINO']
 ..., 
 ['15185'
  'Beca para Poblaciones Vulnerables y en Situaciones Especiales de Formación Técnico Productiva 2015'
  'CAJAMARCA' ..., 'SEDE CAJAMARCA' 'PANADERIA' 'FEMENINO']
 ['15186'
  'Beca para Poblaciones Vulnerables y en Situaciones Especiales de Formación Técnico Productiva 2015'
  'CAJAMARCA' ..., 'SEDE CAJAMARCA' 'PANADERIA' 'FEMENINO']
 ['15188' 'Beca 18 Ordinaria 2015' 'LAMBAYEQUE' ..., 'SEDE CHICLAYO'
  'ADMINISTRACION TURISTICA' 'FEMENINO']]


In [41]:
# La primera fila tiene los nombres de los atributos
feature_names = becarios_dataset[0]
print(feature_names)

['' 'convocatoria' 'region' 'motivo' 'resolucion_ret_beca'
 'fec_resolucion_ret_beca' 'fec_Postulacion' 'tipoinstitucion'
 'institucioneducativa' 'institucionsede' 'carreradescripcion' 'genero']


In [42]:
#vemos la primera tupla del dataset
print (becarios_dataset[1])

['0' 'Beca 18 Modalidad Ordinaria 2012' 'LIMA' '1' 'RESOLUCION JEFATURAL'
 '2014-11' '2012-04' 'Universidad' 'NACIONAL MAYOR DE SAN MARCOS'
 'SEDE LIMA' 'INGENIERIA GEOLOGICA' 'MASCULINO']


In [43]:
# En la columna 3 tenemos la clase que queremos predecir (es decir, el motivo por el cual perdieron la beca)
# Vale 1 si desaprobo, 0 si abandonó. 
becarios_y=becarios_dataset[1:,3].astype(float)
print(becarios_y)

[ 1.  1.  1. ...,  1.  1.  0.]


In [44]:
# Seleccionamos las columnas con las cuales vamos a trabajar:
# 2: region
# 7: tipoinstitucion
# 11: genero
becarios_x = becarios_dataset[1:, [2, 7, 11]]

print(becarios_x[5:10].tolist())
print(becarios_y[5:10].tolist())

[['LIMA', 'Universidad', 'MASCULINO'], ['LIMA', 'Universidad', 'MASCULINO'], ['LIMA', 'Universidad', 'MASCULINO'], ['LIMA', 'Universidad', 'MASCULINO'], ['LIMA', 'Universidad', 'MASCULINO']]
[1.0, 1.0, 1.0, 1.0, 1.0]


In [45]:
# Para trabajar con la libreria sklearn debemos convertir nuestras variables categoricas a numericas
# Para ello utiizaremos los siguientes metodos: LabelEncoder y OneHotEncoder para realizar esta tarea.

from sklearn.preprocessing import LabelEncoder
enc = LabelEncoder()

# Le paso los valores que tengo y el asigna un entero a cada clase posible
# GENERO : MASCULINO,FENENINO los cambios por 1,0
label_encoder = enc.fit(becarios_x[:, 2])
print("Clase Genero:", label_encoder.classes_)

# usamos transform para transformar las clases por los números 0,1
tranform = label_encoder.transform(becarios_x[:, 2])
becarios_x[:, 2] = tranform
print (becarios_x[1].tolist(), becarios_y[1].tolist())

Clase Genero: ['FEMENINO' 'MASCULINO']
['LIMA', 'Universidad', '1'] 1.0


In [46]:
# Para transformar variables categorias que tienen mas de 2 posibles valores usamos OneHotEncoder

# PARA TRANSFORMAR LA COLUMNA REGION

from sklearn.preprocessing import OneHotEncoder   
lencoder = LabelEncoder()
label_encoder = lencoder.fit(becarios_x[:,0])  #Ajuste el codificador de etiquetas
integer_classes = label_encoder.transform(label_encoder.classes_).reshape(31,1) # especificamos el nro de posibles valores

enc = OneHotEncoder()
one_hot_encoder=enc.fit(integer_classes)

# Primero, convierta clases a 0- (N-1) enteros usando el codificador label_encoder
num_of_rows = becarios_x.shape[0]
t = label_encoder.transform(becarios_x[:, 0]).reshape(num_of_rows, 1)

# En segundo lugar, cree una matriz dispersa con tres columnas, cada una indicando si la instancia pertenece a la clase
new_features = one_hot_encoder.transform(t)

# Añadir las nuevas features a becarios_y
becarios_x = np.concatenate([becarios_x, new_features.toarray()], axis = 1)

#Eliminar columnas convertidas
becarios_x = np.delete(becarios_x, [0], 1)

# Actualizar los nombre de las features
feature_names = ['tipoinstitucion','genero','LIMA','JUNIN','LORETO','PIURA',
                 'LA LIBERTAD','CUSCO','AREQUIPA','PUNO','LAMBAYEQUE','AYACUCHO',
                 'SAN MARTIN','CAJAMARCA','PASCO','HUANCAVELICA','TACNA','APURIMAC',
                 'AMAZONAS','ANCASH','UCAYALI','ICA','HUANUCO','MOQUEGUA','CALLAO','MADRE DE DIOS',
                'TUMBES','CUBA','HONDURAS','ESPAÑA','FRANCIA','ARGENTINA','BRASIL']




# Convertir a valores numéricos
#becarios_x = becarios_x.astype(float)

print (becarios_x[0].tolist())

['Universidad', '1', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '1.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0']


In [47]:
# PARA TRANSFORMAR LA COLUMNA TIPO INSTITUCION

from sklearn.preprocessing import OneHotEncoder
lencoder = LabelEncoder()
label_encoder = lencoder.fit(becarios_x[:,0])
integer_classes = label_encoder.transform(label_encoder.classes_).reshape(8,1)

enc = OneHotEncoder()
one_hot_encoder=enc.fit(integer_classes)

# Primero, convierta clases a 0- (N-1) enteros usando el codificador label_encoder
num_of_rows = becarios_x.shape[0]
t = label_encoder.transform(becarios_x[:, 0]).reshape(num_of_rows, 1)

# En segundo lugar, cree una matriz dispersa con tres columnas, cada una indicando si la instancia pertenece a la clase
new_features = one_hot_encoder.transform(t)

# Añadir las nuevas features a becarios_y
becarios_x = np.concatenate([becarios_x, new_features.toarray()], axis = 1)

#Eliminar columnas convertidas
becarios_x = np.delete(becarios_x, [0], 1)

# Actualizar los nombre de las features
feature_names = ['genero','LIMA','JUNIN','LORETO','PIURA',
                 'LA LIBERTAD','CUSCO','AREQUIPA','PUNO','LAMBAYEQUE','AYACUCHO',
                 'SAN MARTIN','CAJAMARCA','PASCO','HUANCAVELICA','TACNA','APURIMAC',
                 'AMAZONAS','ANCASH','UCAYALI','ICA','HUANUCO','MOQUEGUA','CALLAO','MADRE DE DIOS',
                'TUMBES','CUBA','HONDURAS','ESPAÑA','FRANCIA','ARGENTINA','BRASIL',
                 'INSTITUTO DE EDUCACION SUPERIOR TECNOLOGICO',
                 'UNIVERSIDAD','Centro de Educación Técnico-Productiva',
                'Instituto de Educación Superior Pedagógico','Instituto de Idiomas',
                'Instituto','Instituto de Educación Superior','Academia Pre-Universitaria']


    

# Convertir a valores numéricos
becarios_x = becarios_x.astype(float) # Transformamos a float 

print (becarios_x[100].tolist())

[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]


In [48]:
print('Nombre de las nuevas features:',feature_names)
print('Valores:',becarios_x[0])
print('Target(motivo de pérdida):', becarios_y[0])

Nombre de las nuevas features: ['genero', 'LIMA', 'JUNIN', 'LORETO', 'PIURA', 'LA LIBERTAD', 'CUSCO', 'AREQUIPA', 'PUNO', 'LAMBAYEQUE', 'AYACUCHO', 'SAN MARTIN', 'CAJAMARCA', 'PASCO', 'HUANCAVELICA', 'TACNA', 'APURIMAC', 'AMAZONAS', 'ANCASH', 'UCAYALI', 'ICA', 'HUANUCO', 'MOQUEGUA', 'CALLAO', 'MADRE DE DIOS', 'TUMBES', 'CUBA', 'HONDURAS', 'ESPAÑA', 'FRANCIA', 'ARGENTINA', 'BRASIL', 'INSTITUTO DE EDUCACION SUPERIOR TECNOLOGICO', 'UNIVERSIDAD', 'Centro de Educación Técnico-Productiva', 'Instituto de Educación Superior Pedagógico', 'Instituto de Idiomas', 'Instituto', 'Instituto de Educación Superior', 'Academia Pre-Universitaria']
Valores: [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  1.]
Target(motivo de pérdida): 1.0


In [49]:
## HASTA AQUI YA TENENEMOS NUESTROS DATOS LIMPIOS Y PREPROCESADOS

In [51]:
## El proceso de aprendizaje aplicaremos arbol de decision.
## Vamos primero separar el dataset en dos:
## un conjunto de entrenamiento y otro de testeo. 
##  Trabajaremos siempre sobre el de entrenamiento,
##  y dejamos el de testeo para evaluar nuestros resultados. Lo dividimos en 75/25

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(becarios_x, becarios_y, test_size=0.25, random_state=33)

In [52]:
## Usaremos el modelo DecisionTreeClassifier del Arbol de decision

from sklearn import tree
classifier = tree.DecisionTreeClassifier(criterion='entropy', max_depth=3,min_samples_leaf=5)
classifier = classifier.fit(X_train,y_train)

In [53]:
from sklearn import metrics
def measure_performance(X,y,classifier, show_accuracy=True, show_classification_report=True, show_confusion_matrix=True):
    y_pred=classifier.predict(X)   
    if show_accuracy:
        print("Accuracy:{0:.3f}".format(metrics.accuracy_score(y,y_pred)),"\n")

    if show_classification_report:
        print("Classification report")
        print(metrics.classification_report(y,y_pred),"\n")
        
    if show_confusion_matrix:
        print("Confusion matrix")
        print(metrics.confusion_matrix(y,y_pred),"\n")
        
measure_performance(X_train,y_train,classifier, show_classification_report=True, show_confusion_matrix=True)

Accuracy:0.645 

Classification report
             precision    recall  f1-score   support

        0.0       0.61      0.74      0.67      2326
        1.0       0.70      0.55      0.62      2504

avg / total       0.66      0.64      0.64      4830
 

Confusion matrix
[[1732  594]
 [1121 1383]] 



In [54]:
measure_performance(X_test,y_test, classifier, show_classification_report=True, show_confusion_matrix=True)

Accuracy:0.646 

Classification report
             precision    recall  f1-score   support

        0.0       0.63      0.73      0.68       819
        1.0       0.67      0.56      0.61       792

avg / total       0.65      0.65      0.64      1611
 

Confusion matrix
[[595 224]
 [347 445]] 



In [55]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(classifier, X_train, y_train)
print(scores)
print(np.mean(scores))

[ 0.6443203   0.64285714  0.63704164]
0.641406360526
